name: udata_gouvfr Ui-Kit
theme:
  logo: theme/less/images/logo.png
  css:
    - theme/less/theme.css
  sidebar:
    background: "#b8e2ff"
    textColor: "#070d54"
examples:
  css:
    - udata_gouvfr/theme/static/stylemark_temp/less/index.css
    - theme/less/examples.css
  js:
    - udata_gouvfr/theme/static/stylemark_temp/js/index.js
