on:
  push:
    branches:
      - main-theme

jobs:
  deploy-dokku-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # deploy app
      - name: dokku deploy
        id: deploy
        uses: ./.github/actions/dokku-dummy-cd
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HOST: app.etalab.studio
          PROJECT: udata
